name: isomash
description: An isometric experiment (so far).
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.12.0-259.16.beta <3.0.0'

dependencies:
  flame:
    path: ../../../flame/packages/flame
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false

  assets:
    - assets/images/paths.png
    - assets/images/tileset.png
    - assets/images/simple-character.png
